set -ga terminal-overrides ",screen-256color*:Tc"
set-option -g default-terminal "screen-256color"
set -s escape-time 0

unbind C-b
set-option -g prefix C-a
bind-key C-a send-prefix
set -g status-style 'bg=#333333 fg=#5eacd3'

bind r source-file ~/.tmux.conf
set -g base-index 1

set-window-option -g mode-keys vi
bind -T copy-mode-vi v send-keys -X begin-selection
bind -T copy-mode-vi y send-keys -X copy-pipe-and-cancel 'xclip -in -selection clipboard'

# vim-like pane switching
bind -n -r ^ last-window
bind -n -r C-k select-pane -U
bind -n -r C-j select-pane -D
bind -n -r C-h select-pane -L
bind -n -r C-l select-pane -R

# tmux plugins
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'tmux-plugins/tpm'

run '~/.tmux/plugins/tpm/tpm'


# Enable italics in tmux
set -g default-terminal "tmux-256color"
set -as terminal-overrides ',xterm-256color:Tc:smulx=\E[4:3m'

# Mouse
set -g mouse on
